export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIE_VIDEOS = "FETCH_MOVIE_VIDEOS";
export const FETCH_SEARCHED_MOVIES = "FETCH_SEARCHED_MOVIES";
export const FETCH_TVSHOWS = "FETCH_TVSHOWS";
export const FETCH_TVSHOW = "FETCH_TVSHOW";
export const FETCH_TVSHOW_VIDEOS = "FETCH_TVSHOW_VIDEOS";
export const FETCH_SEARCHED_TVSHOWS = "FETCH_SEARCHED_TVSHOWS";
